<a href="https://colab.research.google.com/github/ykamen/CS4342/blob/main/cs4342_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!python --version

Python 3.7.12


In [3]:
import numpy as np

#Part 1

Problem 1

In [ ]:
def p1(A,B):
  if A.shape != B.shape:
    print(f"Can't add two matrices of different sizes; size matrix1: {A.shape}, size matrix2: {B.shape}\n")
    return
  C = A+B
  matrix = np.array(C)
  print(f"{matrix}\n")

In [ ]:
A = np.array([[1,2],[2,2]])
B = np.array([[3,2],[2,2]])
p1(A,B)

C = np.array([[3,2],[2,2],[1,1]])
p1(A,C)

[[4 4]
 [4 4]]

Can't add two matrices of different sizes; size matrix1: (2, 2), size matrix2: (3, 2)



Problem 2

In [ ]:
def p2(A,B,C):
  temp = np.dot(A,B)
  fin = temp - C
  return fin

In [ ]:
A = np.array([[1,2],[2,2]])
B = np.array([[3,2],[2,2]])
print(np.dot(A,B))
C = np.array([[3,4],[1,1]])
p2(A,B,C)

[[ 7  6]
 [10  8]]


array([[4, 2],
       [9, 7]])

Problem 3

In [ ]:
def p3(A,B,C):
  temp = A*B
  temp2 = C.transpose()
  fin = temp + temp2
  return fin

In [ ]:
A = np.array([[1,2],[2,2]])
B = np.array([[3,2],[2,2]])
print(A*B)
C = np.array([[3,4],[1,1]])
p3(A,B,C)

[[3 4]
 [4 4]]


array([[6, 5],
       [8, 5]])

Problem 4

In [ ]:
def p4(x,S,y):
  temp = x.transpose()
  temp2 = temp.dot(S)
  fin = temp2.dot(y)
  return fin

In [ ]:
A = np.array([[1],[2]])
B = np.array([[3,2],[2,2]])
C = np.array([[3],[1]])
p4(A,B,C)

array([[27]])

Problem 5

In [ ]:
def p5(A):
  fin = np.ones(np.shape(A)[0])
  return fin

In [ ]:
A = np.array([[4,2],[4,1],[1,1]])
p5(A)

array([1., 1., 1.])

Problem 6

In [ ]:
def p6(A):
  temp = min(np.shape(A)[0], np.shape(A)[1])
  for i in range(temp):
    A[i][i] = 0
  return A

In [ ]:
A = np.array([[4,2],[4,1],[1,1]])
p6(A)
B = np.array([[4,2,4,2],[4,1,1,1]])
p6(B)

array([[0, 2, 4, 2],
       [4, 0, 1, 1]])

Problem 7

In [ ]:
def p7(A,a):
  temp = np.eye(A.shape[0])
  fin = A + a*temp
  return fin

In [ ]:
A = np.array([[4,2],[4,1]])
a = 3
p7(A,a)

array([[7., 2.],
       [4., 4.]])

Problem 8

In [ ]:
def p8(A,i,j):
  return A[j-1][i-1]
#since we enumerate matrices properly (without starting at 0) included the i-1
#if you didn't want us to do that, specify in the instructions next time please

In [ ]:
A = np.array([[3,2],[4,1]])
p8(A,1,2)

4

Problem 9

In [ ]:
def p9(A,i):
  temp = A.sum(1)
  return temp[i-1]
#same. Ai in my understanding is Ai-1 for pc code. When I ask for row 1 sum,
#it means sum of row 0 for pc.

In [ ]:
A = np.array([[3,1,10],[4,2,4],[4,2,3],[4,3,0]])
p9(A,1)

14

Problem 10

In [ ]:
def p10(A,c,d):
  temp = []
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      if (A[i][j] >= c and A[i][j] <= d):
        temp.append(A[i][j])
  print(temp)
  fin = sum(temp)/len(temp)
  return fin

In [ ]:
A = np.array([[3,1,10],[4,2,4],[4,2,3],[4,3,0]])
c = 3
d = 4
p10(A,c,d)

[3, 4, 4, 4, 3, 4, 3]


3.5714285714285716

Problem 11

In [ ]:
def p11(A,k):
  eigenvalues, eigenvectors = np.linalg.eig(A)
  temp = [x for _,x in sorted(zip(eigenvalues, eigenvectors),reverse= True)]
  fin = np.column_stack(temp[:k])
  print(fin)
  

In [ ]:
A = np.array([[3,1,10,2,5],[4,2,4,1,0],[4,2,3,11,3],[5,2,4,4,5],[1,2,5,7,8]])
p11(A,3)

[[ 0.48723562+0.j          0.44449559+0.j          0.51287092+0.j        ]
 [ 0.68978076+0.j         -0.15232319-0.34149101j  0.17689608+0.1917062j ]
 [ 0.68978076-0.j         -0.15232319+0.34149101j  0.17689608-0.1917062j ]
 [-0.07117561+0.j          0.0157211 +0.j          0.552226  +0.j        ]
 [-0.13973983+0.j         -0.05697462+0.j         -0.26880486+0.j        ]]


Problem 12

In [ ]:
def p12(A,x):
  temp = np.eye(A.shape[0])
  inv = np.linalg.solve(A,temp)
  return inv.dot(x)

In [ ]:
A = np.array([[3,1,10],[4,2,4],[4,2,3]])
x = ([1,2,4])
p12(A,x)

array([ 16., -27.,  -2.])

Problem 13

In [ ]:
def p13(x,k):
  return np.tile(x,(k,1))

In [ ]:
x = [1,2,4,5,7,8]
k = 3
p13(x,k)

array([[1, 2, 4, 5, 7, 8],
       [1, 2, 4, 5, 7, 8],
       [1, 2, 4, 5, 7, 8]])

Problem 14

In [10]:
def p14(A):
  fin = A
  for i in range(A.shape[0]):
    fin[i] = np.random.permutation(A[i])
  return fin

In [11]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
p14(A)

array([[3, 1, 2],
       [6, 4, 5],
       [7, 9, 8]])

#Part 2